name: Publish Container Image

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - chart-integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build Docker image
        run: docker build . -t reviewer-reporter:${{ github.sha }}
      - name: Push image
        if: github.ref == 'refs/heads/master || github.ref == 'refs/heads/chart-integration'
        run: .scripts/github/retag-and-push.sh reviewer-reporter ${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
